language: android
dist: trusty
env:
  global:
    - ANDROID_BUILD_TOOLS=29.0.2
    - ADB_INSTALL_TIMEOUT=5
    - ANDROID_API=29
  matrix:
    - EMULATOR_API=21
    - EMULATOR_API=22
android:
  components:
    - tools
    - platform-tools-$ANDROID_BUILD_TOOLS
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
    - android-$EMULATOR_API
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
    - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API
    - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API
    - sys-img-armeabi-v7a-android-$EMULATOR_API
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
jdk:
  - oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- yes | sdkmanager "platforms;android-$ANDROID_API"
before_script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG
  - echo no | android create avd --force -n test -t android-$EMULATOR_API --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &
script:
  - ./gradlew build rootCodeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)